git:
  quiet: true

branches:
  only:
    - /^dev\/.*$/
    - master

before_install:
  - sudo apt-get -y install sshpass

install: skip

before_script: skip

script: skip

after_success:
  - ./deploy
