#!/bin/bash
imageName='mooncake001/sz-server:latest'

ls
echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
docker build -t $imageName .
docker push $imageName

echo 'image done!'