#!/bin/bash
imageName='mooncake001/sz-server:latest'

sshpass -p $SERVER_PWD ssh -o StrictHostKeyChecking=no root@$SERVER_IP
docker pull $imageName
docker run -p 3333:3333 -d --name sz-test $imageName